SpectraL519/cpp-ap

test/Makefile
Changing *.mk files directory required change of their location in "Makefile" file. This commit includes this change.
=> PWRS5PZ-6: Testing on MacOS

.clang-format, include/ap/argument_parser.hpp, test/testing_friend_definitions.hpp, test/tests/test_argument_parser_add_argument.cpp, test/tests/test_optional_argument.cpp, test/tests/test_positional_argument.cpp
Added:
* the `valid_argument_type` concept
* the `add_argument()` function to the parser class
* all the necessary members
* unit tests covering the added functionality
=> PWRS5PZ-14: Add parser functionality - adding arguments

include/ap/argument_parser.hpp, test/include/argument_parser_test_fixture.hpp, test/include/optional_argument_test_fixture.hpp, test/include/positional_argument_test_fixture.hpp, test/tests/test_argument_name.cpp, test/tests/test_argument_parser_add_argument.cpp, test/tests/test_argument_parser_parse_args.cpp, test/tests/test_optional_argument.cpp, test/tests/test_positional_argument.cpp
Move the following elements to given namespace:
- argument_name                          ->     ap::argument
- argument_interface                     ->     ap::argument::detail
- positional_argument                    ->     ap::argument
- optional_argument                       ->     ap::argument
- all concepts and helper structs    ->     ap::utility
Align tests to use correct namespaces
=> PWRS5PZ-31: Project namespace refinement

example/main.cpp, include/ap/argument_parser.hpp, test/tests/test_argument_parser_parse_args.cpp
Add a `bypass_required()` function to the `optional_argument` class.
This function should set a flag of an argument which enables the option to bypass the requirement of specifying values of positional and `required` optional arguments.
Modify argument parsing to acount for the added functionality.
Modify existing and add new test cases to cover the added functionality
=> PWRS5PZ-34: Bypassing required arguments

example/main.cpp, include/ap/argument_parser.hpp, test/include/argument_parser_test_fixture.hpp, test/include/optional_argument_test_fixture.hpp, test/include/positional_argument_test_fixture.hpp, test/tests/test_argument_name.cpp, test/tests/test_argument_parser_add_argument.cpp, test/tests/test_nargs_range.cpp
1. Added:
* the `add_flag<bool>(name)` function to the parser
* the `ap::defeault_argument` struct
* the `default_{positional/optional}_arguments(vector<default_arg_specifier>)` functions to the argument parser
* explicit enum class underlying types
* tests covering the added functionality
2. Moved the `argument_name` class to the `ap::argument::detail` namespace
=> PWRS5PZ-35: Default arguments

README.md, change_log.md, include/ap/argument_parser.hpp, test/include/argument_parser_test_fixture.hpp, test/source/test_argument_name.cpp, test/source/test_argument_parser_add_argument.cpp, test/source/test_argument_parser_parse_args.cpp, test/source/test_optional_argument.cpp, test/source/test_positional_argument.cpp
* Renamed the `argument_name` structure members:
* `name` -> `primary`
* `short_name` -> `secondary`
* Added the `argument_name::match` functions
* Aligned the code and unit tests to use the new names and functions
=> YT-CPPAP-5: argument_name class refactor

README.md, change_log.md, include/ap/argument_parser.hpp
- Fixed some typos and incorrect examples in the readme file
- Renamed and refactored the `ap::action::check_file_exists_action()` function
=> YT-CPPAP-8: Fix typos and rename some elements

tests/source/test_argument_name.cpp, tests/source/test_argument_parser_add_argument.cpp, tests/source/test_argument_parser_info.cpp, tests/source/test_argument_parser_parse_args.cpp, tests/source/test_optional_argument.cpp, tests/source/test_positional_argument.cpp
Aligned the unit tests to use fixtures and CHECK macros (instead of REQUIRE) where it is appropriate and/or necessary
=> YT-CPPGL-9: Clean up the unit tests

.github/workflows/demo.yaml, .gitmodules, README.md
Added:
- the demo workflow, which builds the `cpp-ap-demo` submodule using the current cpp-ap branch
- the workflow badge in readme
=> YT-CPPG-22: Add the demo workflow

include/ap/argument_parser.hpp, tests/include/argument_parser_test_fixture.hpp, tests/include/optional_argument_test_fixture.hpp, tests/source/test_argument_parser_parse_args.cpp, tests/source/test_optional_argument.cpp, tests/source/test_positional_argument.cpp
In the demo project `numbers_converter` there was a crash:
```
./numbers_converter/run -n 2 10 15 -b
terminate called after throwing an instance of 'ap::error::invalid_value_type_error'
what():  Invalid value type specified for argument [base,b] - NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
Aborted (core dumped)
```
ANALYSIS:
The crash/error is valid, but the error message does not suggest the root cause.
FIX:
Improved the error throwing and handling to provide a more descriptive message.
=> YT-CPPGL-23: Fix the invalid_value_type_error crash when there is no parsed or predefined values for an optional argument

include/ap/argument_parser.hpp, tests/include/argument_parser_test_fixture.hpp, tests/source/test_argument_parser_parse_args.cpp, tests/source/test_optional_argument.cpp
- Removed redundant documentation comments
- Aligned constructor and operator declarations order
- Replaced `var++` with `++var` where appropriate
- Replaced `vec.push_back` with `vec.emplace_back` where appropriate
- Replaced `c_equality_comparable` with `std::equality_comparable` and changed the definition of `c_argument_value_type` to use `std::semiregular`
=> NONE: Initial cleanup for the v1.3 release

include/ap/argument_parser.hpp, tests/include/argument_parser_test_fixture.hpp, tests/source/test_argument_parser_parse_args.cpp
Changed the name of the `argument_parser::cmd_argument` struct to `arg_token` and aligned related elements
=> YT-CPPAP-25: Rename the cmd_argument struct to token

README.md, include/ap/argument/optional.hpp, include/ap/argument/positional.hpp, include/ap/argument_parser.hpp, include/ap/detail/concepts.hpp, tests/include/optional_argument_test_fixture.hpp, tests/include/positional_argument_test_fixture.hpp, tests/source/test_optional_argument.cpp, tests/source/test_positional_argument.cpp
Modified the `choices` functions of the positional and optional arguments to take as input an instance of `std::initializer_list` or a `std::ranges::range` type the value type of which is convertible to the argument's `value_type`
=> YT-CPPAP-33: Extend the choices initialization

README.md, include/ap/argument_parser.hpp
- Added the range-based overload of the `parse_args` method, which defines the parsing logic
- Aligned the `parse_args(argc, argv)` method to call the range-based function with a span constructed from `argc` and `argv`
=> YT-CPPAP-31: Add range-based parsing argument

CMakeLists.txt, README.md, cmake/cpp-ap-2-config.cmake.in, include/ap/argument_parser.hpp, tests/CMakeLists.txt
- Introduced the minor value in the version tags
- Changed the CMake target names to `cpp-ap-2`
- Added the `try_parse_args` and `handle_help_action` functions to the `argument_parser` class
=> CPP-AP: version 2.0.0

include/ap/action/predefined_actions.hpp, include/ap/argument/optional.hpp, include/ap/argument/positional.hpp, include/ap/argument_parser.hpp, include/ap/error/exceptions.hpp, tests/source/test_argument_parser_add_argument.cpp
Adder the argument name verification functionality to the `argument_parser` class - an error is thrown if `argument_parser::add_*` is called with a name that:
- is empty
- begins with the flag prefix character
- begins with a digit
=> YT-CPPAP-34: Add argument name pattern verification

CMakeLists.txt, Doxyfile, docs/tutorial.md, include/ap/argument/optional.hpp, include/ap/argument/positional.hpp, include/ap/argument_parser.hpp, include/ap/detail/argument_descriptor.hpp, include/ap/detail/argument_interface.hpp, include/ap/detail/str_utility.hpp, include/ap/error/exceptions.hpp, include/ap/nargs/range.hpp, tests/include/optional_argument_test_fixture.hpp, tests/include/positional_argument_test_fixture.hpp, tests/include/utility.hpp, tests/source/test_argument_parser_parse_args.cpp, tests/source/test_nargs_range.cpp, tests/source/test_optional_argument.cpp, tests/source/test_positional_argument.cpp, tests/source/test_str_utility.cpp
- Any values passed for an optional argument which exceed the upper bound specified with the `nargs` parameter will now be treated as dangling and an error will be thrown immediately instead of at the end during the verification step
- Improved argument name formatting in error messages
- Changed the default `nargs` parameter value to `nargs::any()` - unbound range
=> YT-CPPAP-36: Improve value assignment logic

CMakeLists.txt, Doxyfile, include/ap/argument/optional.hpp, include/ap/argument/positional.hpp, include/ap/argument_parser.hpp, include/ap/detail/argument_base.hpp, tests/include/optional_argument_test_fixture.hpp, tests/include/positional_argument_test_fixture.hpp, tests/include/utility.hpp, tests/source/test_argument_parser_add_argument.cpp, tests/source/test_optional_argument.cpp, tests/source/test_positional_argument.cpp
- Renamed the `argument_interface` class to `argument_base`
- Move common/default functionality of the `positional` and `optional` classes to the base class
=> YT-CPPAP-38: Argument base class alignment

.github/workflows/documentation.yaml, CMakeLists.txt, Doxyfile, LICENSE.md, README.md, docs/dev_notes.md, docs/tutorial.md, doxygen-ext-stylesheet.css, scripts/check_version.py, scripts/postprocess_doxyhtml.py
- Added the documentation postprocessing script, which:
- fixes the markdown file links, GFM-style callouts, heading code blocks
- removes the mainpage title generated by doxygen
- Aligned the documentation workflow to:
- validate that the current cmake and doxygen version matches the created tag
- apply the postprocessing step to the generated documentation
- upload the current version to the `latest` directory as well as to the <version> directory if the current tag is actually the latest
- Aligned the docs to include the proper explanation of how to generate and browse the documentation
- Aligned the indentation in docs so that they are properly handeled by doxygen
- Added the repository link to the docomuentation main page (readme)
=> YT-CPPAP-41: Documentation deployment refinement

CMakeLists.txt, Doxyfile, include/ap/argument_parser.hpp, include/ap/detail/argument_name.hpp, include/ap/detail/argument_token.hpp, tests/CMakeLists.txt, tests/include/argument_parser_test_fixture.hpp, tests/source/test_argument_name.cpp, tests/source/test_argument_parser_parse_args.cpp
- Introduced the `match_type` enum class to specify how the argument name should be matched
- Split the `t_flag` argument token to `t_flag_primary` and `t_flag_secondary`
- Aligned the argument parsing implementation to match the specified flags properly:
`--` flags are matched only to the primary names and `-` flags only to the secondary names
=> Split argument name matching

.bazelrc, .github/workflows/clang.yaml, .github/workflows/demo.yaml, .github/workflows/gcc.yaml, .github/workflows/msvc.yaml, BUILD, BUILD.bazel, CMakeLists.txt, Doxyfile, MODULE.bazel, README.md, cmake/cpp-ap-config.cmake.in, docs/tutorial.md, include/ap/argument_parser.hpp, scripts/check_version.py, tests/CMakeLists.txt
- Added the `MODULE.bazel`, `BUILD.bazel` and `.bazelrc` configuration files
- Aligned the `check_version` script to verify the Bazel module version
- Reverted the naming of the CMake library target back to `cpp-ap` instead of `cpp-ap-2` to better match the naming of the Bazel module
- Updated the `cpp-ap-demo` submodule: added the Bazel configuration files to enable building the demo projects using Bazel
- Updated the `demo` workflow to build the demo projects using both CMake and Bazel and on both Linux and Windows platforms
=> [none] Bazel build system support

.gitignore, CMakeLists.txt, Doxyfile, MODULE.bazel, docs/tutorial.md, include/ap/argument_parser.hpp, include/ap/detail/typing_utility.hpp, include/ap/exceptions.hpp
- Implemented type name demangling functionality
- Added the parametrized `type_error` class builder functions which use the type demangling functionality
=> YT-CPPAP-49: Use demandgled type names

CMakeLists.txt, Doxyfile, MODULE.bazel, docs/tutorial.md, include/ap/argument/optional.hpp, include/ap/argument/positional.hpp, include/ap/argument_parser.hpp, include/ap/detail/argument_base.hpp, include/ap/exceptions.hpp, tests/include/optional_argument_test_fixture.hpp, tests/include/positional_argument_test_fixture.hpp, tests/source/test_optional_argument.cpp, tests/source/test_positional_argument.cpp
Added the `hidden` attribute setter to the positional and optional argument classes. 
If an argument is declared hidden, it will not be included in the program description generated by the argument parser.
=> YT-CPPAP-48: Add support for argument hiding

CMakeLists.txt, Doxyfile, MODULE.bazel, README.md, docs/tutorial.md, include/ap/argument_parser.hpp, include/ap/detail/argument_descriptor.hpp, include/ap/detail/argument_token.hpp, include/ap/detail/typing_utility.hpp, include/ap/version.hpp, tests/include/argument_parser_test_fixture.hpp, tests/source/test_argument_parser_info.cpp, tests/source/test_argument_parser_parse_args.cpp
Modified the command-line tokenization logic to try to split unknown secondary flag arguments into multiple secondary argument flag tokens (one for each character of the unknown flag).
Example: If the program defines an argument with a secondary name `v`, then `-vvv` would be equivalent to `-v -v -v`, unless the program also defines a `-vvv` argument.
Additional:
- Added support for declaring the program version
- Optimized argument lookup during argument tokenization and parsing stages
=> YT-CPPAP-46: Add compound argument flags support

CMakeLists.txt, Doxyfile, MODULE.bazel, include/ap/argument_parser.hpp, include/ap/detail/argument_token.hpp, include/ap/detail/concepts.hpp, tests/include/argument_parser_test_fixture.hpp, tests/source/test_argument_parser_add_argument.cpp, tests/source/test_argument_parser_parse_args.cpp, tests/source/test_argument_token.cpp
- Replaced `std::unique_ptr` with `std::shared_ptr` in the argument lists within `argument_parser`
- Replaced optional argument reference type with `std::shared_ptr`
- Previously: `std::optional<std::reference_wrapper<std::unique_ptr<argument_base>>>` 
- Aligned argument token building to store original (unstripped) command-line values
- Defined a *parsing state* structure within `argument_parser` to replace passing multiple parsing parameters by reference with a single compound type
=> YT-CPPAP-62: Argument parsing improvement
